const fs = require('fs');

// 1. Fix tokenCookie fallback
let path = 'website/src/lib/tokenCookie.ts';
let content = fs.readFileSync(path, 'utf8');
content = content.replace(
    `    const secret = process.env.TOKEN_ENCRYPTION_SECRET || 'default_dev_secret_change_me_now';`,
    `    const secret = process.env.TOKEN_ENCRYPTION_SECRET;
    if (!secret) throw new Error('TOKEN_ENCRYPTION_SECRET is missing');`
);
content = content.replace(
    `        const secret = process.env.TOKEN_ENCRYPTION_SECRET || 'default_dev_secret_change_me_now';`,
    `        const secret = process.env.TOKEN_ENCRYPTION_SECRET;
        if (!secret) throw new Error('TOKEN_ENCRYPTION_SECRET is missing');`
);
fs.writeFileSync(path, content, 'utf8');

// 2. Fix GoogleAuthManager
path = 'app/src/main/java/com/neubofy/reality/google/GoogleAuthManager.kt';
content = fs.readFileSync(path, 'utf8');
content = content.replace(
    `    private fun getPrefs(context: Context) =
        com.neubofy.reality.utils.SecurePreferences.get(context, PREF_NAME)`,
    `    private fun getPrefs(context: Context) =
        com.neubofy.reality.utils.SecurePreferences.get(context, PREF_NAME)

    private fun getConnectorPrefs(context: Context) =
        com.neubofy.reality.utils.SecurePreferences.get(context, "google_connector_prefs")`
);
// replace other usages in GoogleAuthManager.kt for google_connector_prefs
content = content.replace(/context\.getSharedPreferences\("google_connector_prefs", Context\.MODE_PRIVATE\)/g, 'getConnectorPrefs(context)');
fs.writeFileSync(path, content, 'utf8');

// 3. Re-do privacy policy update
path = 'website/src/app/privacypolicy/page.tsx';
content = fs.readFileSync(path, 'utf8');
const searchBlock2 = `            <h3>1. Local, Offline Nature of Reality</h3>
            <p>Reality is designed to be an offline, local-first application. We do not have user accounts, cloud databases, or servers storing your personal data. Your usage patterns, settings, timers, and application logs are stored exclusively on your device.</p>`;
const replaceBlock2 = `            <h3>1. Local-First Architecture</h3>
            <p>Reality is local-first. The Android app does not send your personal productivity data to Neubofy servers. The website is hosted on Vercel and uses serverless routes for OAuth redirection and public pages. We do not maintain a user account database or store Google credentials in a database. Your usage patterns, settings, timers, and application logs are stored exclusively on your device.</p>`;
content = content.replace(searchBlock2, replaceBlock2);

const searchBlock3 = `            <h3>2. Data Collection</h3>
            <p>Because there is no backend server, Neubofy does not collect, harvest, or transmit your personal data. Any data generated by Reality remains entirely within the isolated storage of the app on your phone. If you uninstall the app or clear its data, your information is permanently deleted and cannot be recovered by us.</p>`;
const replaceBlock3 = `            <h3>2. Data Collection</h3>
            <p>Because there is no central backend database for app data, Neubofy does not collect, harvest, or transmit your personal productivity data. Any data generated by Reality remains entirely within the isolated storage of the app on your phone. If you uninstall the app or clear its data, your information is permanently deleted and cannot be recovered by us. Health and app usage data is sensitive and local-first unless you explicitly send/export it or permit AI access.</p>`;
content = content.replace(searchBlock3, replaceBlock3);

const searchBlock4 = `            <h3>6. External Services and Third Parties</h3>
            <p>Reality may contain links or integrate with external APIs (e.g., if you choose to connect a Google Calendar or use a custom AI endpoint). In such cases, your interaction with those services is governed by their respective privacy policies. Reality acts merely as a client passing your requests; we do not intercept or store this third-party data on any external servers.</p>`;
const replaceBlock4 = `            <h3>6. External Services and Third Parties</h3>
            <p>Reality may contain links or integrate with external APIs. For example, if you connect Google Calendar in the Tapashya Web App, the authorization token is encrypted and stored locally as a secure HttpOnly browser cookie to keep you connected safely. Google tokens are not exposed to frontend JavaScript, and you can disconnect at any time. AI features may send selected context (which you permit) to your chosen AI provider. The Pro Members page may publicly display your User ID and join date if you participate in Reality Pro. Reality acts merely as a client passing your requests; we do not intercept or store your calendar data or AI conversations on our servers.</p>`;
content = content.replace(searchBlock4, replaceBlock4);
fs.writeFileSync(path, content, 'utf8');

// 4. Re-do TOS update
path = 'website/src/app/termsofservice/page.tsx';
content = fs.readFileSync(path, 'utf8');
const searchBlock5 = `              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Privacy and Data Security</h2>
                <p>Reality is built on a local-first philosophy. We do not store, transmit, or have access to your personal data, app usage, or configurations on any central server. All data remains exclusively on your device. Consequently, we cannot recover lost data under any circumstances.</p>
              </section>`;
const replaceBlock5 = `              <section>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Privacy and Data Security</h2>
                <p>Reality is built on a local-first philosophy. The Android app does not transmit your personal data to our servers. All app data remains exclusively on your device. Consequently, we cannot recover lost data under any circumstances. For web services, like Tapashya Google Calendar integration, we use secure, encrypted cookies and Vercel serverless routes without storing your credentials in a database. AI features transmit data securely to your chosen provider only when triggered.</p>
              </section>`;
content = content.replace(searchBlock5, replaceBlock5);
fs.writeFileSync(path, content, 'utf8');
