name: Build Release APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle


      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          if [ ! -z "$KEYSTORE_BASE64" ]; then
            echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
          fi

      - name: Configure local.properties
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REALITY_LICENSE_URL: ${{ secrets.REALITY_LICENSE_URL }}
        run: |
          touch local.properties
          echo "KEYSTORE_FILE=keystore.jks" >> local.properties
          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> local.properties
          echo "KEY_ALIAS=$KEY_ALIAS" >> local.properties
          echo "KEY_PASSWORD=$KEY_PASSWORD" >> local.properties
          echo "DEFAULT_CLIENT_ID=$CLIENT_ID" >> local.properties
          echo "DEFAULT_CLIENT_SECRET=$CLIENT_SECRET" >> local.properties
          echo "REALITY_LICENSE_URL=$REALITY_LICENSE_URL" >> local.properties

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build_v4/outputs/apk/release/*.apk

      - name: Extract Version
        id: get_version
        run: |
          VERSION_NAME=$(grep "versionName =" app/build.gradle.kts | awk -F'"' '{print $2}')
          echo "VERSION_NAME=v$VERSION_NAME" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          tag_name: ${{ env.VERSION_NAME }}
          name: Release ${{ env.VERSION_NAME }}
          files: app/build_v4/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
